### ISSUE TITLE
How to validate pseudo label

### ISSUE THREAD

**Issue by nguyenkimnhatminh13** [astra-vision/PaSCo#11]
Dear Mr. @anhquancao ,

Thank you for your work, shout out for the Vietnamese.

I am doing research based on your work, but i have problem validating your pseudo label, how did you achieve this metric performance for the pseudo label as below.
![image](https://github.com/user-attachments/assets/5227cad9-e3c6-4e90-8498-ad7540b23c15)

Thank you very much,
Nhật Minh

**Comment by nguyenkimnhatminh13** [comment]
For clarity i am talking about pseudo label available in https://github.com/astra-vision/PaSCo/releases/download/v0.0.1/kitti_instance_label_v2.tar.gz

> 1. Voxelize the single-frame point cloud.
> 2. Utilize the pseudo-label to generate predictions for the voxelized point cloud.
> 3. Since the Semantic KITTI dataset provides the panoptic label for the point cloud, we can derive the label for the voxelized point cloud.

Is the code for generating panoptic prediction available in the repo? If so can you show me?

Thank you very much,
Nhật Minh

**Comment by anhquancao** [comment]
Sorry, I don't plan to release the code for that part.
