### ISSUE TITLE
Hi, I confronted this problem while doing 4.1.2 training

### ISSUE THREAD

**Issue by qiuxiam** [astra-vision/PaSCo#15]
File "/home/selfdriving/PaSCo/pasco/data/semantic_kitti/kitti_dataset.py", line 370, in load_data_v3
    (xyz[:, 0] < self.max_extent[0])
UnboundLocalError: local variable 'xyz' referenced before assignment

**Comment by anhquancao** [comment]
Hi, did you run [this step](https://github.com/astra-vision/PaSCo?tab=readme-ov-file#411-extract-point-features)?

**Comment by qiuxiam** [comment]
yes

**Comment by anhquancao** [comment]
Please check if this[ path variable here](https://github.com/astra-vision/PaSCo/blob/main/pasco/data/semantic_kitti/kitti_dataset.py#L345) contain correct path
