### ISSUE TITLE
Issue with Code Loading the Semantic KITTI Dataset

### ISSUE THREAD

**Issue by YuanZhao42** [astra-vision/PaSCo#16]
Is the labels used in Semantic KITTI from the [SemanticKITTI label data (179 MB)](https://www.semantic-kitti.org/dataset.html#download) or from the labels in the [SemanticKITTI voxel data (700 MB)](https://www.semantic-kitti.org/dataset.html#download)? It seems that the code in [kitti_dataset.py](https://github.com/astra-vision/PaSCo/blob/main/pasco/data/semantic_kitti/kitti_dataset.py) does not use the labels from the voxel data.

Additionally, the code in [kitti_dataset.py](https://github.com/astra-vision/PaSCo/blob/main/pasco/data/semantic_kitti/kitti_dataset.py)  references poses.txt. Is this file from the [Download odometry ground truth poses (4 MB)](https://www.cvlibs.net/datasets/kitti/eval_odometry.php) on the KITTI odometry benchmark page?

**Comment by anhquancao** [comment]
Hi @YuanZhao42, you're correct - the voxel data is used to [generate panoptic labels](https://github.com/astra-vision/PaSCo?tab=readme-ov-file#3-panoptic-labels-generation). The `kitti_dataset.py` script only loads the extracted panoptic labels.

Regarding the `poses.txt` file from the KITTI dataset, it's not actually in use anymore; I should have removed it. It was initially used for testing scenarios where the input point cloud was an accumulation of several scans.

Apologies for the confusion -- I didn’t have enough time to fully clean up the code before releasing it.
