### ISSUE TITLE
Problems with extracting point cloud features

### ISSUE THREAD

**Issue by jmwang0117** [astra-vision/PaSCo#19]
Thank you for your excellent work. I encountered a problem when extracting point cloud features.
1. I encountered:
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/Semantic_KITTI/dataset/sequences/00/labels/000000.label'
As far as I know, label is under voxels, and there is no separate label file?
![image](https://github.com/user-attachments/assets/ae6b7b75-05ed-422b-a0b3-7e42b182bd17)

2. But when I modify semanticKITTI, modifying labels to voxles will appear
Unable to load batch["pc_orig"], what is this?

![image](https://github.com/user-attachments/assets/4d71e66c-dc7a-4a3a-9c09-47ddcca02a54)

**Comment by anhquancao** [comment]
Hi @jmwang0117,
The labels come from the "The[ KITTI Odometry Benchmark](http://www.cvlibs.net/datasets/kitti/eval_odometry.php) Velodyne data (Download odometry data set (velodyne laser data, 80 GB))."

You should not replace it with voxels.

**Comment by anhquancao** [comment]
Hi @jmwang0117 ,

It is in fact the "[Download](https://www.semantic-kitti.org/assets/data_odometry_labels.zip) SemanticKITTI label data (179 MB)" from https://www.semantic-kitti.org/dataset.html#download 
Sorry for forgeting to mention it in the [data section](https://github.com/astra-vision/PaSCo?tab=readme-ov-file#21-semantic-kitti).
