### ISSUE TITLE
CUDA capability

### ISSUE THREAD

**Issue by jmwang0117** [astra-vision/PaSCo#20]
Thanks for your great work, I tried to extract point cloud features on RTX3090 and A800, but encountered this error:

![image](https://github.com/user-attachments/assets/5d72f273-18a1-4cd0-9210-97e2f227f162)

Pytorch 1.11 cannot be used on RTX3090 and A800, sm_86. How do you extract features?

**Comment by jmwang0117** [comment]
When I upgraded to pytorch 1.13, another error appeared:

![image](https://github.com/user-attachments/assets/ff130713-b2af-4efa-b9c2-730d8dffa469)

**Comment by anhquancao** [comment]
Hi,
Can you try to set `--batch_size 1`
