### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by jmwang0117** [astra-vision/PaSCo#22]
Thanks for your great work!

I use two A800-80Gs for training. It can train correctly with **one subnet**, but the following error occurs with **three subnets**. Is there any way to solve this problem?

![image](https://github.com/user-attachments/assets/0058b975-f72e-433f-a404-0c678752ffa9)

![image](https://github.com/user-attachments/assets/993b3fe7-5cf3-4cfa-a64a-821c36c36e87)

**Comment by anhquancao** [comment]
Hi, I've never seen this error. Looks like there is an error when calling .max() function from pytorch. Did you use the same version of pytorch?

**Comment by jmwang0117** [comment]
I use pytorch 2.1.0+cu121

**Comment by anhquancao** [comment]
The  code was tested with pytorch 1.13, probably this could be the reason.
