### ISSUE TITLE
Training terminates after pruning generates an empty SparseTensor

### ISSUE THREAD

**Issue by WAAutomation** [astra-vision/PaSCo#24]
Thanks for your outstanding work!
During training, this function returns an empty 'keep' (pasco/models/decoder_v3.py, line 319),  which means Semantic Head predicts all voxels as non-occupied.
![image](https://github.com/user-attachments/assets/0a614516-60f3-4d6c-9459-07409369c42a)
This empty 'keep' will cause errors in subsequent training.

I found a similar function that didn't used in the project, this function has an additional condition to check if 'keep' is empty. (pasco/models/decoder_v3.py, line 290)
![image](https://github.com/user-attachments/assets/6c7e466c-4a93-42e8-a836-92e7440952df)

I wonder why 'predict_completion_sem_logit' is used instead of 'predict_completion' in the latest version and how to solve the aforesaid issue when using 'predict_completion_sem_logit'.

**Comment by anhquancao** [comment]
Hi,
predict_completion directly predicts occupied/empty voxels, while predict_completion_sem_logit first predicts the semantic class and then converts it to occupied/empty.
I added a check [here](https://github.com/astra-vision/PaSCo/blob/main/pasco/models/decoder_v3.py#L385), but the issue still occurs during some training runs, especially when using multiple subnets. I haven’t been able to fully resolve this problem yet.

**Comment by WAAutomation** [comment]
Thanks for your response.
I add a min_occ_thres to restrict the minimum number of voxels in 'keep' and it seems worked
![image](https://github.com/user-attachments/assets/b7c0a47e-e30d-46ac-88d8-85c289738a45)
