### ISSUE TITLE
About the annotations and code

### ISSUE THREAD

**Issue by ttomtom6** [astra-vision/PaSCo#3]
Hi~ congratulations to you for PaSCo  being accepted by CVPR! I would like to know when the relevant annotations and code will be available.

**Comment by anhquancao** [comment]
Hello! Thank you for your interest. I've planned the code release for May. However, if it's crucial for you, I can make the annotations and dataloader available earlier, by the end of next week.

**Comment by willemeng** [comment]
> Hello! Thank you for your interest. I've planned the code release for May. However, if it's crucial for you, I can make the annotations and dataloader available earlier, by the end of next week.

Hi,  it is very outstanding work. When will the annotation data and dataloade be made public?

**Comment by anhquancao** [comment]
Hello, I apologize for the delay. I've been quite occupied recently, but I'm planning to make the data and dataloader available by the next weekend. I put it on my todo list.

**Comment by anhquancao** [comment]
Hi @willemeng , @ttomtom6 
I've made the label generation for KITTI and part of the data loader available. The project will continue to be released gradually through the end of May.

**Comment by ttomtom6** [comment]
Hi @anhquancao , thanks for your updates. Could you please consider open-sourcing the evaluation metric calculations? I'd like to benchmark my model using your benchmarks for performance on panoptic and uncertainty metrics.

**Comment by anhquancao** [comment]
Sure, I will prioritise open-sourcing it.

**Comment by anhquancao** [comment]
Hi, I released the training and evaluation code for PaSCo w/o MIMO. The remaining code will be released soon.
