### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by Edric-star** [astra-vision/PaSCo#7]
Hi, I confronted this problem while doing 4.1.2 training, are there any other libraries or packages that you could offer to help?Thank you so much! I switched my conda env to pasco while doing this...
---------------------------------------------------------------------------
    from uncertainty.models.metrics import SSCMetrics
ModuleNotFoundError: No module named 'uncertainty'

**Comment by anhquancao** [comment]
Thanks for reporting the bug. Sorry about the name error. I've fixed it and pushed the update. Please try again.

**Comment by Edric-star** [comment]
I tried pip install uncertainty and it turned out(I'm not pretty sure) a fail and I supposed it might be the problem of the version of numpy because my numpy is 1.25.2 which's not the same as the numpy==1.20 in requirements.txt because if I did pip intall requirements.txt, it would reported as follows:

```
The conflict is caused by:
The user requested numpy==1.20
h5py 3.7.0 depends on numpy>=1.14.5
imageio 2.33.1 depends on numpy
numba 0.58.1 depends on numpy<1.27 and >=1.22
```

Then I set a numpy==1.25 to fit this problem and I guess it might be a possible mistake later, but I'm really confused.Mr. Cao, could you please review your requirements.txt and check the 'uncertainty' module? I really appreciate your work and that's why I started running the model as soon as you updated these days.

**Comment by Edric-star** [comment]
> Thanks for reporting the bug. Sorry about the name error. I've fixed it and pushed the update. Please try again.

Oh my god...thank you for your immediate replay！I would try again soon

**Comment by anhquancao** [comment]
You should install a lower version of numba to be able to install NumPy 1.20. Recent NumPy versions use float instead of np.float, which causes problems with the code.

**Comment by Edric-star** [comment]
> Collaborator
Thanks, I got it fixed. By the way, would you decide to release the eval code that's able to generate the completed label? I mean the Panoptic scene completion.

**Comment by anhquancao** [comment]
Hi, you can find the code for [generating the panoptic label here](https://github.com/astra-vision/PaSCo/tree/main?tab=readme-ov-file#3-panoptic-labels-generation).

**Comment by Edric-star** [comment]
I did notice that later and that's why I closed the comment, anyway thanks!
