### ISSUE TITLE
Dataset input form

### ISSUE THREAD

**Issue by Edric-star** [astra-vision/PaSCo#8]
```
/gpfsdswork/dataset/SemanticKITTI/dataset/
    └── sequences/
        └── 01/
            ├── labels/
            ├── velodyne/
            ├── voxels/
            ├── calib.txt
            ├── poses.txt
            └── times.txt
```
Hi there, should the dataset form goes like this? It's a little bit different from what's been posted in ReadMe file

**Comment by anhquancao** [comment]
Yes, you are right. Actually, we don't need poses.

**Comment by Edric-star** [comment]
Hello, I have successfully run 'eval.py' with semanticKITTI. When will you update the code to generate the completed scene files? I am eagerly looking forward to it! I would greatly appreciate it.

**Comment by anhquancao** [comment]
Hi, do you mean [this section](https://github.com/astra-vision/PaSCo?tab=readme-ov-file#3-panoptic-labels-generation)?

**Comment by Edric-star** [comment]
> Hi, do you mean [this section](https://github.com/astra-vision/PaSCo?tab=readme-ov-file#3-panoptic-labels-generation)?

Sorry, I think this part seems to be about generating some panoramic labels, that is, files with added instance labels. I might still be learning and have some gaps in my understanding of this part. Could you please confirm if this is the final result of the scene generation?

**Comment by Edric-star** [comment]
Maybe I was talking about this part `5. Visualization` in your ReadMe file as I just noticed, I would like to check the effect of the output completion files, just like these pics in your paper.
![image](https://github.com/astra-vision/PaSCo/assets/78262981/204430ba-a492-4093-9747-c9edef12a202)

**Comment by Edric-star** [comment]
Thanks for the update

**Comment by anhquancao** [comment]
Hi @Edric-star, I added visualization [code here](https://github.com/astra-vision/PaSCo?tab=readme-ov-file#5-visualization).
