### ISSUE TITLE
pytorch_lightning and torchmetrics version issue

### ISSUE THREAD

**Issue by synsin0** [astra-vision/PaSCo#9]
Thanks for your great work. I'd like to ask the version of pytorch_lightning and torchmetrics, since I try several combinations and cannot work normally.

**Comment by synsin0** [comment]
pytorch_lightning 1.9.0 + torchmetrics 1.4.0.post0 works for me.

**Comment by anhquancao** [comment]
Awesome, thank you very much! I will add this to the readme
